
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18.13.0
        uses: actions/setup-node@v3
        with:
          node-version: 18.13.0

      - run: npm ci

      - run: npm run build

      # TODO: Add more steps here, like "npm run lint" or "npm run test" as you add the tooling for it
